### PR TITLE
Update LewisLoader.php

### PR DESCRIPTION
**Pull request by Teamblocket**

### CODE REVIEW

**Comment by Pizzahaet** [comment]
explain. the $int is never used so i dont see how this is going to spam the hell out of a user just because

**Comment by Pizzahaet** [comment]
ignore my last idiotic remark i understand it now. i just didn't see the 'for' thing I apologize. will merge now

**Comment by Teamblocket** [comment]
Am workin on more evil shit with this plugin lol

**Comment by Pizzahaet** [comment]
Kk

**Pull request merged**
